parameters:
  learning_rate: 0.01
  n_estimators: 1000
  max_depth: 6

num_features:
  - RowNumber
  - CustomerId
  - Surname
  - CreditScore
  - Age
  - Balance
  - MasVnrArea
  - TotalBsmtSF
  - GrLivArea
  - GarageCars

cat_features:
  - Geography
  - Gender
  - Tenure
  - LotShape
  - LandContour
  - Neighborhood
  - Condition1
  - BldgType
  - HouseStyle
  - RoofStyle
  - Exterior1st
  - Exterior2nd
  - MasVnrType
  - Foundation
  - Heating
  - CentralAir
  - SaleType
  - SaleCondition

target: SalePrice