catalog_name: mlops_prod
schema_name: churn_predictor

parameters:
  learning_rate: 0.01
  n_estimators: 1000
  max_depth: 6

num_features:
  - CreditScore
  - Age
  - Balance
  - IsActiveMember

cat_features:
  - France
  - Germany
  - Spain
  - Female
  - Male
  - NumOfProducts1
  - NumOfProducts2
  - NumOfProducts3
  - NumOfProducts4

target: Exited

ab_test:
  test_group: A
  control_group: B

pipeline_id: pipeline_12345